import pool from '../config/db.js';

export const seedGreensboroBusinesses = async () => {
  try {

    const businesses = [
      // Food & Dining
      {
        name: 'The New Summit Cafe',
        category: 'Food & Dining',
        description: 'Breakfast and lunch spot featuring egg and meat combos, pancakes, waffles, burgers, and daily specials.',
        address: '1050 Summit Ave',
        city: 'Greensboro',
        state: 'NC',
        zip_code: '27405',
        phone: '(336) 274-9876',
        email: 'info@newsummitcafe.com',
        website: 'https://www.newsummitcafe.com',
        hours: JSON.stringify({ 'Mon-Fri': '6:30am-2pm', 'Sat': '7am-2pm', 'Sun': 'Closed' }),
        latitude: 36.0892,
        longitude: -79.8034,
        image_url: 'https://images.unsplash.com/photo-1495521821757-a1efb6729352?w=400&h=300&fit=crop',
        community_tags: JSON.stringify(['Breakfast', 'Local'])
      },
      {
        name: 'Gillespie Grill',
        category: 'Food & Dining',
        description: 'Family-focused restaurant known for its turkey BBQ plates and other signature dishes.',
        address: '601 Milner Dr',
        city: 'Greensboro',
        state: 'NC',
        zip_code: '27410',
        phone: '(336) 299-4567',
        email: 'info@gillespiegrille.com',
        website: 'https://www.gillespiegrill.com',
        hours: JSON.stringify({ 'Mon-Thu': '11am-9pm', 'Fri-Sat': '11am-10pm', 'Sun': '11am-8pm' }),
        latitude: 36.0745,
        longitude: -79.8156,
        image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561621?w=400&h=300&fit=crop',
        community_tags: JSON.stringify(['BBQ', 'Family-Owned'])
      },
      {
        name: "'Cille & 'Scoe",
        category: 'Food & Dining',
        description: 'A restaurant redefining southern cuisine in downtown Greensboro.',
        address: '312 S Elm St',
        city: 'Greensboro',
        state: 'NC',
        zip_code: '27401',
        phone: '(336) 516-7890',
        email: 'info@cilleandscoe.com',
        website: 'https://www.cilleandscoe.com',
        hours: JSON.stringify({ 'Mon-Thu': '11am-10pm', 'Fri-Sat': '11am-11pm', 'Sun': '10am-9pm' }),
        latitude: 36.0656,
        longitude: -79.7904,
        image_url: 'https://images.unsplash.com/photo-1504674900892-afb209cf6d46?w=400&h=300&fit=crop',
        community_tags: JSON.stringify(['Southern', 'Downtown', 'Fine Dining'])
      },
      {
        name: 'Hickory Tree BBQ',
        category: 'Food & Dining',
        description: 'Specializes in turkey smoked over hickory wood with a health-conscious approach.',
        address: '2804 Randleman Rd',
        city: 'Greensboro',
        state: 'NC',
        zip_code: '27406',
        phone: '(336) 545-1234',
        email: 'info@hickorytreebbq.com',
        website: 'https://www.hickorytreebbq.com',
        hours: JSON.stringify({ 'Mon-Sat': '11am-8pm', 'Sun': 'Closed' }),
        latitude: 36.0512,
        longitude: -79.8245,
        image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561621?w=400&h=300&fit=crop',
        community_tags: JSON.stringify(['BBQ', 'Healthy'])
      },
      {
        name: 'Boss Hog Bar-B-Que',
        category: 'Food & Dining',
        description: 'A cash-only BBQ joint with lunch and dinner specials.',
        address: '2314 E Bessemer Ave',
        city: 'Greensboro',
        state: 'NC',
        zip_code: '27405',
        phone: '(336) 271-5555',
        email: 'info@bosshogbbq.com',
        website: 'https://www.bosshogbbq.com',
        hours: JSON.stringify({ 'Mon-Sat': '10:30am-8pm', 'Sun': 'Closed' }),
        latitude: 36.0634,
        longitude: -79.7654,
        image_url: 'https://images.unslash.com/photo-1518909578529-2d4ee01c6c23?w=400&h=300&fit=crop',
        community_tags: JSON.stringify(['BBQ', 'Casual'])
      },
      {
        name: 'Luxe Soulfood and Cocktails',
        category: 'Food & Dining',
        description: 'A premier soul food restaurant in the heart of Greensboro.',
        address: '403 N Elm St',
        city: 'Greensboro',
        state: 'NC',
        zip_code: '27401',
        phone: '(336) 333-9988',
        email: 'info@luxesoulfood.com',
        website: 'https://www.luxesoulfood.com',
        hours: JSON.stringify({ 'Mon-Thu': '5pm-10pm', 'Fri-Sat': '5pm-11pm', 'Sun': '12pm-9pm' }),
        latitude: 36.0721,
        longitude: -79.7905,
        image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop',
        community_tags: JSON.stringify(['Soul Food', 'Downtown', 'Upscale'])
      },
      {
        name: 'Calypso Mama Caribbean Cafe',
        category: 'Food & Dining',
        description: 'Caribbean cuisine featuring traditional island flavors and fresh ingredients.',
        address: '1600 Phillips Ave',
        city: 'Greensboro',
        state: 'NC',
        zip_code: '27403',
        phone: '(336) 312-4556',
        email: 'info@calypso-mama.com',
        website: 'https://www.calypso-mama.com',
        hours: JSON.stringify({ 'Tue-Thu': '11am-9pm', 'Fri-Sat': '11am-10pm', 'Sun': '12pm-8pm', 'Mon': 'Closed' }),
        latitude: 36.0876,
        longitude: -79.8167,
        image_url: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400&h=300&fit=crop',
        community_tags: JSON.stringify(['Caribbean', 'International'])
      },
      {
        name: 'King-Queen Haitian Cuisine',
        category: 'Food & Dining',
        description: 'Authentic Haitian food bringing Caribbean flavors to Greensboro.',
        address: '1800 Spring Garden St',
        city: 'Greensboro',
        state: 'NC',
        zip_code: '27403',
        phone: '(336) 275-2233',
        email: 'info@kingqueenhaitian.com',
        website: 'https://www.kingqueenhaitian.com',
        hours: JSON.stringify({ 'Tue-Sun': '11am-9pm', 'Mon': 'Closed' }),
        latitude: 36.0789,
        longitude: -79.7845,
        image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop',
        community_tags: JSON.stringify(['Haitian', 'Caribbean'])
      },
      {
        name: 'House Divided Bottles and Taps',
        category: 'Food & Dining',
        description: 'Serves beers on tap along with bottled beer, ciders, and wine, and hosts community events.',
        address: '616 Dolley Madison Rd',
        city: 'Greensboro',
        state: 'NC',
        zip_code: '27408',
        phone: '(336) 478-4456',
        email: 'info@housedividedbottles.com',
        website: 'https://www.housedividedbottles.com',
        hours: JSON.stringify({ 'Tue-Thu': '4pm-11pm', 'Fri-Sat': '4pm-12am', 'Sun': '12pm-9pm', 'Mon': 'Closed' }),
        latitude: 36.1145,
        longitude: -79.7834,
        image_url: 'https://images.unsplash.com/photo-1608270861620-7911c88a85a0?w=400&h=300&fit=crop',
        community_tags: JSON.stringify(['Bar', 'Beer', 'Events'])
      },
      // Bakeries & Sweets
      {
        name: 'Savor the Moment Bakery',
        category: 'Bakeries & Sweets',
        description: 'A three-generation family-owned bakery and dessert cafe known for crunch cheesecakes, cookies, ice cream, and more.',
        address: '124 N Davie St',
        city: 'Greensboro',
        state: 'NC',
        zip_code: '27401',
        phone: '(336) 274-7890',
        email: 'info@savorthemoment.com',
        website: 'https://www.savorthemoment.com',
        hours: JSON.stringify({ 'Mon-Sat': '8am-6pm', 'Sun': '12pm-5pm' }),
        latitude: 36.0721,
        longitude: -79.7934,
        image_url: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&h=300&fit=crop',
        community_tags: JSON.stringify(['Bakery', 'Family-Owned', 'Desserts'])
      },
      {
        name: "AJ's Cheesecakes",
        category: 'Bakeries & Sweets',
        description: 'A family-owned cheesecake manufacturer producing high-quality artisan cheesecakes.',
        address: '414 E Market St',
        city: 'Greensboro',
        state: 'NC',
        zip_code: '27401',
        phone: '(336) 279-5555',
        email: 'info@ajscheesecakes.com',
        website: 'https://www.ajscheesecakes.com',
        hours: JSON.stringify({ 'Mon-Fri': '9am-5pm', 'Sat': '10am-3pm', 'Sun': 'Closed' }),
        latitude: 36.0656,
        longitude: -79.7745,
        image_url: 'https://images.unsplash.com/photo-1533134242443-742f6e4d2877?w=400&h=300&fit=crop',
        community_tags: JSON.stringify(['Cheesecake', 'Artisan'])
      },
      {
        name: 'Something BARowed Candy Bar Stations',
        category: 'Bakeries & Sweets',
        description: 'Creates customized candy bar stations for events, plus candy favor bags and gift baskets.',
        address: '412 E Market St',
        city: 'Greensboro',
        state: 'NC',
        zip_code: '27401',
        phone: '(336) 278-6666',
        email: 'info@somethingbarrowed.com',
        website: 'https://www.somethingbarrowed.com',
        hours: JSON.stringify({ 'Mon-Fri': '10am-5pm', 'Sat': 'By Appointment', 'Sun': 'Closed' }),
        latitude: 36.0655,
        longitude: -79.7743,
        image_url: 'https://images.unsplash.com/photo-1599599810694-b5ac4dd53c4f?w=400&h=300&fit=crop',
        community_tags: JSON.stringify(['Candy', 'Events', 'Custom'])
      },
      // Beauty, Hair & Wellness
      {
        name: 'Shear Passion Hair Studio',
        category: 'Beauty, Hair & Wellness',
        description: 'A multicultural salon catering to all ethnicities and genders with expert stylists.',
        address: '710 W Market St',
        city: 'Greensboro',
        state: 'NC',
        zip_code: '27401',
        phone: '(336) 303-1111',
        email: 'info@shearpassion.com',
        website: 'https://www.shearpassion.com',
        hours: JSON.stringify({ 'Tue-Sat': '10am-6pm', 'Sun': '1pm-5pm', 'Mon': 'Closed' }),
        latitude: 36.0634,
        longitude: -79.8045,
        image_url: 'https://images.unsplash.com/photo-1559599810-46d1c9dcb4d5?w=400&h=300&fit=crop',
        community_tags: JSON.stringify(['Hair', 'Salon', 'Multicultural'])
      },
      {
        name: "The Queen's Royal Beauty Bar",
        category: 'Beauty, Hair & Wellness',
        description: 'Full-service hair salon offering cuts, styles, and treatments.',
        address: '315 E Market St',
        city: 'Greensboro',
        state: 'NC',
        zip_code: '27401',
        phone: '(336) 282-7777',
        email: 'info@queenroyalbeauty.com',
        website: 'https://www.queenroyalbeauty.com',
        hours: JSON.stringify({ 'Tue-Sat': '9am-6pm', 'Sun': '12pm-4pm', 'Mon': 'Closed' }),
        latitude: 36.0662,
        longitude: -79.7722,
        image_url: 'https://images.unsplash.com/photo-1574258495688-dcb89a0ad66e?w=400&h=300&fit=crop',
        community_tags: JSON.stringify(['Hair', 'Beauty', 'Salon'])
      },
      {
        name: 'Salon Crie: A Textured Hair Salon',
        category: 'Beauty, Hair & Wellness',
        description: "Greensboro's premier textured hair studio specializing in natural and textured hair care.",
        address: '217 Summit Ave',
        city: 'Greensboro',
        state: 'NC',
        zip_code: '27405',
        phone: '(336) 292-3333',
        email: 'info@saloncrie.com',
        website: 'https://www.saloncrie.com',
        hours: JSON.stringify({ 'Wed-Sat': '10am-6pm', 'Sun': '12pm-4pm', 'Mon-Tue': 'Closed' }),
        latitude: 36.0892,
        longitude: -79.8034,
        image_url: 'https://images.unsplash.com/photo-1522336572468-37505b721b11?w=400&h=300&fit=crop',
        community_tags: JSON.stringify(['Hair', 'Natural', 'Textured Hair'])
      },
      {
        name: 'La Facial Hair & Nail Salon',
        category: 'Beauty, Hair & Wellness',
        description: 'Professional facial and nail services in a relaxing environment.',
        address: '424 E Market St',
        city: 'Greensboro',
        state: 'NC',
        zip_code: '27401',
        phone: '(336) 285-4444',
        email: 'info@lafacial.com',
        website: 'https://www.lafacial.com',
        hours: JSON.stringify({ 'Mon-Sat': '10am-7pm', 'Sun': '12pm-5pm' }),
        latitude: 36.0658,
        longitude: -79.7735,
        image_url: 'https://images.unsplash.com/photo-1604625894917-19f99f481664?w=400&h=300&fit=crop',
        community_tags: JSON.stringify(['Nails', 'Facial', 'Beauty'])
      },
      {
        name: 'Dudley Cosmetology University',
        category: 'Beauty, Hair & Wellness',
        description: 'A beauty school that has helped cosmetology and natural hair care professionals since 1972.',
        address: '519 S Elm St',
        city: 'Greensboro',
        state: 'NC',
        zip_code: '27401',
        phone: '(336) 256-7000',
        email: 'admissions@dudley.edu',
        website: 'https://www.dudley.edu',
        hours: JSON.stringify({ 'Mon-Fri': '8am-5pm', 'Sat-Sun': 'Closed' }),
        latitude: 36.0621,
        longitude: -79.7905,
        image_url: 'https://images.unsplash.com/photo-1560807707-e5b8b7e6f58b?w=400&h=300&fit=crop',
        community_tags: JSON.stringify(['Education', 'Beauty School', 'Historic'])
      },
      {
        name: 'Nur Aesthetics',
        category: 'Beauty, Hair & Wellness',
        description: 'An aesthetics and medical wellness practice offering skincare and rejuvenation treatments.',
        address: '405 Battleground Ave, Ste 105',
        city: 'Greensboro',
        state: 'NC',
        zip_code: '27408',
        phone: '(336) 333-5555',
        email: 'info@nurastheticsnc.com',
        website: 'https://www.nurastheticsnc.com',
        hours: JSON.stringify({ 'Mon-Fri': '9am-5pm', 'Sat': '10am-2pm', 'Sun': 'Closed' }),
        latitude: 36.1089,
        longitude: -79.7845,
        image_url: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=400&h=300&fit=crop',
        community_tags: JSON.stringify(['Wellness', 'Medical', 'Aesthetics'])
      },
      {
        name: 'Allure Teeth Whitening',
        category: 'Beauty, Hair & Wellness',
        description: 'Teeth whitening business with over 10 years of experience using professional-grade treatments.',
        address: '121 S Elm St, Ste D',
        city: 'Greensboro',
        state: 'NC',
        zip_code: '27401',
        phone: '(336) 288-6666',
        email: 'info@allureteeth.com',
        website: 'https://www.allureteeth.com',
        hours: JSON.stringify({ 'Mon-Fri': '9am-6pm', 'Sat': '10am-4pm', 'Sun': 'Closed' }),
        latitude: 36.0614,
        longitude: -79.7905,
        image_url: 'https://images.unsplash.com/photo-1605558912579-3f18a4955b4e?w=400&h=300&fit=crop',
        community_tags: JSON.stringify(['Dental', 'Whitening', 'Beauty'])
      },
      // Retail & Shopping
      {
        name: 'The Black Belt Soap Company',
        category: 'Retail & Shopping',
        description: 'Handcrafted soap and skincare products made in small batches for freshness and efficacy.',
        address: '416 E Market St',
        city: 'Greensboro',
        state: 'NC',
        zip_code: '27401',
        phone: '(336) 289-7777',
        email: 'info@blackbeltsoap.com',
        website: 'https://www.blackbeltsoap.com',
        hours: JSON.stringify({ 'Mon-Sat': '11am-6pm', 'Sun': '12pm-5pm' }),
        latitude: 36.0657,
        longitude: -79.7747,
        image_url: 'https://images.unsplash.com/photo-1600857062241-98e5dba7214d?w=400&h=300&fit=crop',
        community_tags: JSON.stringify(['Soap', 'Skincare', 'Artisan'])
      },
      {
        name: 'Hypeclinic',
        category: 'Retail & Shopping',
        description: 'Streetwear, vintage clothing, and accessories shop for fashion enthusiasts.',
        address: '300 S Elm St',
        city: 'Greensboro',
        state: 'NC',
        zip_code: '27401',
        phone: '(336) 380-2222',
        email: 'info@hypeclinic.com',
        website: 'https://www.hypeclinic.com',
        hours: JSON.stringify({ 'Mon-Sat': '11am-7pm', 'Sun': '12pm-6pm' }),
        latitude: 36.0634,
        longitude: -79.7905,
        image_url: 'https://images.unsplash.com/photo-1567521464027-f127ff144326?w=400&h=300&fit=crop',
        community_tags: JSON.stringify(['Streetwear', 'Vintage', 'Fashion'])
      },
      {
        name: 'Standout Vintage',
        category: 'Retail & Shopping',
        description: 'Curated vintage clothing shop with unique finds and timeless pieces.',
        address: '536 S Elm St',
        city: 'Greensboro',
        state: 'NC',
        zip_code: '27401',
        phone: '(336) 381-3333',
        email: 'info@standoutvintage.com',
        website: 'https://www.standoutvintage.com',
        hours: JSON.stringify({ 'Mon-Sat': '11am-6pm', 'Sun': '12pm-5pm' }),
        latitude: 36.0614,
        longitude: -79.7905,
        image_url: 'https://images.unsplash.com/photo-1541272537190-0ace89b0da6b?w=400&h=300&fit=crop',
        community_tags: JSON.stringify(['Vintage', 'Clothing', 'Downtown'])
      },
      {
        name: 'Stitch, LLC',
        category: 'Retail & Shopping',
        description: 'Made-to-measure clothing and fine accessories for men offering custom tailoring services.',
        address: '420 S Elm St',
        city: 'Greensboro',
        state: 'NC',
        zip_code: '27401',
        phone: '(336) 382-4444',
        email: 'info@stitch-greensboro.com',
        website: 'https://www.stitch-greensboro.com',
        hours: JSON.stringify({ 'Tue-Sat': '10am-6pm', 'Sun-Mon': 'Closed' }),
        latitude: 36.0624,
        longitude: -79.7905,
        image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop',
        community_tags: JSON.stringify(['Tailoring', 'Men', 'Custom'])
      },
      {
        name: 'African American Art & More',
        category: 'Retail & Shopping',
        description: 'A family-owned gallery specializing in Black art and artists, operating since 1989.',
        address: '410 S Elm St',
        city: 'Greensboro',
        state: 'NC',
        zip_code: '27401',
        phone: '(336) 373-5555',
        email: 'info@aaartandmore.com',
        website: 'https://www.aaartandmore.com',
        hours: JSON.stringify({ 'Tue-Sat': '11am-6pm', 'Sun': '1pm-5pm', 'Mon': 'Closed' }),
        latitude: 36.0629,
        longitude: -79.7905,
        image_url: 'https://images.unsplash.com/photo-1579783902614-e3fb5141b0cb?w=400&h=300&fit=crop',
        community_tags: JSON.stringify(['Art Gallery', 'Black Art', 'Family-Owned'])
      },
      // Services & Professional
      {
        name: 'Sharpe Pursuits Incorporated (SP3)',
        category: 'Services & Professional',
        description: 'An event-planning company founded in 1999 with a full-time staff of wedding planners, event designers, DJs, and producers.',
        address: '500 S Elm St',
        city: 'Greensboro',
        state: 'NC',
        zip_code: '27401',
        phone: '(336) 299-2000',
        email: 'info@sharpepursuits.com',
        website: 'https://www.sharpepursuits.com',
        hours: JSON.stringify({ 'Mon-Fri': '9am-5pm', 'Sat-Sun': 'By Appointment' }),
        latitude: 36.0614,
        longitude: -79.7905,
        image_url: 'https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?w=400&h=300&fit=crop',
        community_tags: JSON.stringify(['Event Planning', 'Weddings', 'Professional'])
      },
      {
        name: 'Monte Edwards Group (MEG), LLC',
        category: 'Services & Professional',
        description: 'A project and program management firm offering consulting, facilities management, and disaster recovery services.',
        address: '502 S Elm St',
        city: 'Greensboro',
        state: 'NC',
        zip_code: '27401',
        phone: '(336) 301-3000',
        email: 'info@meg-llc.com',
        website: 'https://www.meg-llc.com',
        hours: JSON.stringify({ 'Mon-Fri': '8am-5pm', 'Sat-Sun': 'Closed' }),
        latitude: 36.0616,
        longitude: -79.7905,
        image_url: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=300&fit=crop',
        community_tags: JSON.stringify(['Management', 'Consulting', 'Professional'])
      },
      {
        name: 'Keith Law & Associates',
        category: 'Services & Professional',
        description: 'Legal practice covering criminal law, family law, personal injury, and civil litigation.',
        address: '100 S Elm St',
        city: 'Greensboro',
        state: 'NC',
        zip_code: '27401',
        phone: '(336) 373-7777',
        email: 'info@keithlaw.com',
        website: 'https://www.keithlaw.com',
        hours: JSON.stringify({ 'Mon-Fri': '9am-5pm', 'Sat-Sun': 'By Appointment' }),
        latitude: 36.0614,
        longitude: -79.7905,
        image_url: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=400&h=300&fit=crop',
        community_tags: JSON.stringify(['Legal', 'Law Firm', 'Professional'])
      },
      {
        name: 'Skymount Studios',
        category: 'Services & Professional',
        description: 'A full-service recording studio with over 14 years of experience, having worked with Grammy-winning and platinum-selling artists.',
        address: '205 S Lyndon St',
        city: 'Greensboro',
        state: 'NC',
        zip_code: '27401',
        phone: '(336) 275-8888',
        email: 'info@skymountstudios.com',
        website: 'https://www.skymountstudios.com',
        hours: JSON.stringify({ 'Mon-Fri': '10am-6pm', 'Sat': '12pm-6pm', 'Sun': 'Closed' }),
        latitude: 36.0656,
        longitude: -79.7934,
        image_url: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400&h=300&fit=crop',
        community_tags: JSON.stringify(['Recording', 'Music', 'Professional'])
      },
      // Culture & Community
      {
        name: 'Magnolia House',
        category: 'Culture & Community',
        description: 'A historic events venue, restaurant, and bed & breakfast, and one of the few remaining Green Book sites in North Carolina.',
        address: '442 Gorrell St',
        city: 'Greensboro',
        state: 'NC',
        zip_code: '27406',
        phone: '(336) 274-6420',
        email: 'info@magnoliahousegreensboro.com',
        website: 'https://www.magnoliahousegreensboro.com',
        hours: JSON.stringify({ 'Mon-Thu': '11am-9pm', 'Fri-Sat': '11am-10pm', 'Sun': '11am-8pm' }),
        latitude: 36.0989,
        longitude: -79.8234,
        image_url: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=400&h=300&fit=crop',
        community_tags: JSON.stringify(['Historic', 'Restaurant', 'Events', 'Green Book'])
      },
      {
        name: 'International Civil Rights Center & Museum',
        category: 'Culture & Community',
        description: 'Located at the former Woolworth\'s building, the site of the famous 1960 sit-in protest.',
        address: '134 S Elm St',
        city: 'Greensboro',
        state: 'NC',
        zip_code: '27401',
        phone: '(336) 274-9199',
        email: 'info@sitinmuseum.org',
        website: 'https://www.sitinmuseum.org',
        hours: JSON.stringify({ 'Mon-Sat': '10am-5pm', 'Sun': '1pm-5pm' }),
        latitude: 36.0634,
        longitude: -79.7905,
        image_url: 'https://images.unsplash.com/photo-1569307211693-3acdc6a0797f?w=400&h=300&fit=crop',
        community_tags: JSON.stringify(['Museum', 'History', 'Civil Rights', 'Historic'])
      }
    ];

    // Insert businesses
    for (const business of businesses) {
      await pool.query(
        `INSERT INTO businesses (
          name, category, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, image_url, community_tags
        ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)`,
        [
          business.name,
          business.category,
          business.description,
          business.address,
          business.city,
          business.state,
          business.zip_code,
          business.phone,
          business.email,
          business.website,
          business.hours,
          business.latitude,
          business.longitude,
          business.image_url,
          business.community_tags
        ]
      );
    }

    console.log('✓ Greensboro businesses seeded successfully');
  } catch (error) {
    console.error('Error seeding Greensboro businesses:', error);
  }
};
